### ISSUE TITLE
Race condition when using 1+ shards

### ISSUE THREAD

**Issue by pizzafox** [T0TProduction/BLAPI#16]
This affects the pr/14 branch.

When the `handle()` function is called, it uses the passed in client object to get the shard (if existent), and then calls `fetchClientValues()`. If all shards aren't ready, this throws an error and fails to post the information.

This happens because shards are started at a delay. If shard 0 doesn't call `handle()` when every shard is ready, this will error every time. The solution is to wait until all shards are ready before running the `fetchClientValues` code.

Normally, you might think 'Just use the event that runs when all the shards are ready.' That event doesn't exist, though. The only way to dynamically wait before calling the function is to write your own implementation of an `allShardsReady` event or some other way of waiting for every shard to get ready.

Another, a simpler solution would be to just wait 45 or so seconds before calling the function and hope your shards are ready then.

**Comment by T0TProduction** [comment]
should be fixed

**Comment by pizzafox** [comment]
Is not fixed, same error.
