### ISSUE TITLE
Metalist rebranding

### ISSUE THREAD

**Issue by pizzafox** [T0TProduction/BLAPI#6]
Metalist rebranded to BotBlock, the package should be updated as the URL for the API has changed.

**Comment by advaith1** [comment]
True but its not really important since the API still works on metalist.xyz

**Comment by MattIPv4** [comment]
Yeah the metalist.xyz domain will work for some time but is deprecated.
PR #7 updates everything and also removes two lists that have shutdown and been removed from BotBlock.

**Comment by T0TProduction** [comment]
I'm still on vacation for another two weeks and won't have access to npm, but after that i'll adjust the code 👌🏻
